### ISSUE TITLE
有相关论文发表吗?

### ISSUE THREAD

**Issue by notastudio** [Revan-github/Fatigue-Driven-Detection-Based-on-CNN#4]
您好,想了解一下这项研究有论文发表吗?

**Comment by Revan-github** [comment]
您对这个东西有兴趣？

**Comment by notastudio** [comment]
我是学生,如果有论文的话就想学习一下你的方法.

**Comment by Revan-github** [comment]
没，这就是个毕业论文的实验，我不做这个方向了。
不知道你说的方法是指什么
CNN应该有很多人做过了吧。我用的是ssd。

**Comment by acubaaa** [comment]
学长/学姐您好😄我正在做疲劳驾驶的大创项目，对于模型不太懂，所以下载了您的模型想自己跑一跑试试看。但是现在环境有些问题，我看到您标注了python是3.7，pytorch是1.0.1，那么您的numpy是什么版本？cuda是什么版本呢？目前cuda我已经装了三个版本，都是不匹配，numpy中的包也有问题，也正在挨个降级尝试。如果您能看到，希望您可以告知我这些包的版本，谢谢您啦🙇‍👼❤
