### ISSUE TITLE
您好，请教一下您一些具体包的运行环境

### ISSUE THREAD

**Issue by acubaaa** [Revan-github/Fatigue-Driven-Detection-Based-on-CNN#5]
学长/学姐您好😄我正在做疲劳驾驶的大创项目，对于模型不太懂，所以下载了您的模型想自己跑一跑试试看。但是现在环境有些问题，我看到您标注了python是3.7，pytorch是1.0.1，那么您的numpy是什么版本？cuda是什么版本呢？目前cuda我已经装了三个版本，都是不匹配，numpy中的包也有问题，也正在挨个降级尝试。如果您能看到，希望您可以告知我这些包的版本，谢谢您啦🙇‍👼❤

**Comment by Revan-github** [comment]
时间太长我也忘了，而且电脑也重装过好几次。cuda应该是9到8之间的版本，numpy没太注意，当时是用anaconda装的python环境然后配置的pytorch 和cuda。pytorch和cuda的版本应该是有一些对应关系的，你可以看一下。anaconda或许也会告诉你一些依赖关系。

**Comment by acubaaa** [comment]
好哒，我去anaconda里看一看❤

**Comment by Revan-github** [comment]
所以，你测试出来了吗？  可以的话我把这一块加到readme里面。

**Comment by acubaaa** [comment]
> 
> 
> 所以，你测试出来了吗？ 可以的话我把这一块加到readme里面。

尝试了几个，尽管换了源，有的包也不是很好下载，最终都是以失败而告终。所以在本地PyCharm上没有跑成功，但是我在Google Colab上跑的，是可以跑出来的，不需要配环境。
另外请问一下学长/学姐，您做这个项目的 时候听过哪些课、看过哪些资料呢？kaggle上有疲劳驾驶的题目，但是知识存在漏洞看不太懂，所以找了一些课程看。目前已经把吴恩达的CNN部分看完了，现在看CS231N（字幕是机器翻译的没有吴恩达的那么清楚），有点看不懂，不知道该如何下手。想请问一下学长/学姐当时怎么学习的👼？

**Comment by Revan-github** [comment]
我当时看了看CNN有关的博客和pytorch中文的神经网络搭建教程吧。自学了一些python的基础操作。
